name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          distributions: "adopt"
          java-version: 19
      - name: clean build
        run: ./gradlew clean test --info --stacktrace